sudo: required

services:
  - docker

install:
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:80 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - curl http://127.0.0.1:80
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

